// Toggle visibility
show_game_info = false;

// Store the full text from the image
text_lines = [
    "NOID",
	"(Use up and down arrows to move text)",
    " NOID is a",
    "dungeon-crawling adventure game",
    "developed by Karl Olma and Jonathan",
    "Gurkan using GameMaker Studio 2.",
    "Dive into an action-packed world",
    "where you explore mysterious dungeons,",
    "defeat enemies, and capture Power Cards.",
    "",
    "Lore",
    "This is not a story about you,",
    "you are only a cog in this world’s",
    "dark hollowed-out machine.",
    "The machines have taken over,",
    "they do have souls, but they got",
    "corrupted. The never-ending red string,",
    "The Circle, floats above us.",
    "Its light corrupts the machines,",
    "makes them angry and jealous of",
    "real flesh and blood.",
    "The only feeling in your chest",
    "is revenge. Roaming through the caverns",
    "wanting to kill them all.",
    "That is your goal.",
    "It won’t make things better,",
    "and you know that.",
    "Still you push forward, push",
    "yourself through the caves,",
    "push your swords into the enemy.",
    "Hoping to find peace.",
    "",
    "Maybe there is still hope for",
    "our kind, even though we were",
    "the ones to shatter it.",
    "",
    "Features",
    "Dungeon: Conquer dungeons filled",
    "with challenges.",
    "Combat System: Engage in battles",
    "against enemies and powerful bosses.",
    "Upgrade System: Collect Power Cards",
    "to enhance your character’s Health,",
    "Stamina, Strength, and Defense.",
    "Each category features up to six",
    "upgrades, allowing for strategic",
    "customization.",
    "Challenging Gameplay: Plan your",
    "upgrades carefully—each Power Card",
    "can only be used for up to three",
    "or four upgrades.",
    "Explore the dungeon and uncover",
    "its secrets.",
    "Defeat enemies and bosses to",
    "gather Power Cards.",
    "",
    "Gameplay Mechanics",
    "Game controls:",
    "You control the player with WASD",
    "and mouse buttons which leads to",
    "easy to master controls.",
    "You attack with left mouse button,",
    "while Shift helps you to escape",
    "dodgy situations with a great dash.",
    "The player (who's name is unknown)",
    "hence the name NOID, has two swords.",
    "He can attack with them and parry",
    "enemy attacks.",
    "Player health is 100 hitpoints",
    "but can be upgraded with Power Cards.",
    "Enemy hitpoints vary between 2 and 7",
    "hitpoints depending on the type of enemy.",
    "",
    "Characters:",
    "Player:",
    "The player is a girl dressed in yellow.",
    "She has two swords and has the ability",
    "to attack and parry with the swords.",
    "She has a ton of attacks she can do.",
    "And she looks really good.",
    "",
    "Enemies:",
    "B.O.T: A robot with two attacks:",
    "Fire dash and shoot.",
    "Flamethrower: Uses his flamethrower",
    "to damage the player.",
    "Flower: Hides in the ceiling and",
    "attacks with steam.",
    "Flashbang: A suicide bomber enemy",
    "that explodes near the player.",
    "Mage: The most complex enemy in the",
    "game with three attack moves.",
    "",
    "Bosses:",
    "Every 3 or 4 rooms there will be a",
    "bossfight that the player needs to defeat",
    "to get a Power Card for an upgrade.",
    "Inspired by Legend of Zelda where",
    "every dungeon boss gives a Heart Container.",
    "",
    "Room design:",
    "Instead of a traditional level design,",
    "we went for a progressive room design.",
    "The player wakes up in his first dungeon",
    "and learns the basic movement, combat,",
    "and parkour.",
    "We plan to make 10 rooms in total.",
    "",
    "Environment:",
    "You start in a dark cave,",
    "then move to a more open city",
    "environment after defeating the",
    "first boss.",
    "",
    "Gameplay and balance:",
    "To maintain balance, enemies will",
    "give rewards based on difficulty.",
    "Rewards could be Slices of Power,",
    "coins, health, or stamina.",
    "Three Slices of Power = 1 Power Card.",
    "",
    "Upgrade Categories with Power Cards:",
    "Health: Increases survivability.",
    "Stamina: Improves endurance for",
    "dodging or running.",
    "Strength: Boosts attack power.",
    "Defense: Enhances ability to take hits.",
    "",
    "Controls, Cheats and Extras",
    "Controls:",
    "Move with WASD",
    "Attack with Left Mouse Button",
    "Dash with Shift",
    "Jump with Space",
    "",
    "Cheats:",
    "Use F12 to toggle developer mode.",
    "In developer mode:",
    "1,2,3 to jump between rooms.",
    "Hold X to disable collision.",
    "Press C to enable wall climb.",
    "Restart room with R.",
    "Restart game with T.",
    "Test sound with J.",
    "Secret test room with Y.",
    "Make HP 1 with L.",
    "Kill all enemies instantly with K.",
    "",
    "Secret entrances are hidden",
    "throughout the game.",
    "",
    "Development Team",
    "Karl: Developer",
    "Jonathan: Developer",
    "",
    "Status:",
    "NOID is currently in development.",
    "Stay tuned for updates, new features,",
    "improvements, and bug fixes.",
    "We are planning to finish a playable",
    "version of the game on February 7th,",
    "and the first chapter on March 6th.",
    "After the deadline, NOID will",
    "continue as a hobby project."
];

// Scrolling properties
scroll_y = 0;
scroll_speed = 5;
line_height = 30;
text_width = 600; // Adjust to fit your screen
max_scroll = array_length(text_lines) * line_height;

