// Toggle visibility
show_game_info = false;

// Store the full text from the image
text_lines = [
    "NOID",
	"",
	"(Use up and down arrows to move text)",
	"",
    "NOID is a dungeon-crawling adventure game",
    "developed by Karl Olma and Jonathan Gurkan using GameMaker Studio 2.",
    "Dive into an action-packed world where you explore a ",
    "mysterious cave somewhere in the future",
    "",
	"",
	"LORE:",
    "This is not a story about you, you are only a cog in this world’s",
    "dark hollowed-out machine. The machines have taken over,",
    "they do have souls, but they got corrupted. The never-ending red string,",
    "The Circle, floats above us. Its light corrupts the machines,",
    "makes them angry and jealous of real flesh and blood.",
    "The only feeling in your chest is revenge. Roaming through the caverns",
    "wanting to kill them all. That is your goal.",
    "It won’t make things better, and you know that.",
    "Still you push forward, push yourself through the caves,",
    "push your swords into the enemy. Hoping to find peace.",
    "Maybe there is still hope for our kind, even though we were",
    "the ones to shatter it.",
    "",
	"",
    "GAME CONTROLS:",
    "You control the player with WASD and mouse buttons which leads to easy to master controls.",
    "You attack with left mouse button, while Shift helps you to escape dodgy situations with a great dash.",
    "The player (who's name is unknown) hence the name NOID, has two swords. She can attack with them and parry enemy attacks.",
    "Player health is 100 hitpoints but can be upgraded with Power Cards.",
    "Enemy hitpoints vary between 2 and 7 hitpoints depending on the type of enemy.",
    "",
	"",
	"ENEMIES",
    "B.O.T: A robot with two attacks: Fire dash and shoot.",
    "Flamethrower: Uses his flamethrower to damage the player.",
    "Flower: Hides in the ceiling and attacks with steam.",
    "Flashbang: A suicide bomber enemy that explodes near the player.",
    "Mage: The most complex enemy in the game with three attack moves.",
    "",
	"TIPS",
	"-Jump over the enemy to doge attacks",
	"-Your wallhooks are forgiving.",
	"you can ledge onto almost any surface",
	"",
	"",
    "CONTROLS:",
    "Move with WASD",
    "Attack with Left Mouse Button",
    "Dash with Shift",
    "Jump with Space",
	"E to use objects or open doors",
    "",
	"",
    "CHEATS:",
    "Use F12 to toggle developer mode.",
    "In developer mode:",
    "1,2,3 to jump between rooms.",
    "Hold X to disable collision.",
    "Press C to enable wall climb.",
    "Restart room with R.",
    "Restart game with T.",
    "Test sound with J.",
    "Secret test room with Y.",
    "Make HP 1 with L.",
    "Kill all enemies instantly with K.",
    "Secret entrances are hidden throughout the game.",
    "",
	"",
    "DEVELOPEMENT TEAM:",
    "Karl: Developer + Graphic design",
    "Jonathan: Developer",
    "",
	"",
	"",
	"If you find this hard to read, please visit our GitHub page for a more detailed README.",
	"Go to https://github.com/JonathanGurkan/NOID for the full README"
];

// Scrolling properties
scroll_y = 0;
scroll_speed = 5;
line_height = 30;
text_width = 600; // Adjust to fit your screen
max_scroll = array_length(text_lines) * line_height;

